### ISSUE TITLE
Add Batted Ball Velocities

### ISSUE THREAD

**Issue by cpsievert** [cpsievert/pitchRx#29]
[Baseball savant](http://baseballsavant.com/pitchfx_search.php) has them and [apparently they are the gameday site](https://twitter.com/ClownHypothesis/status/604300544144986112), but where are they located?

**Comment by dlependorf** [comment]
Oh man, this would be a godsend. Wish I knew where the files were, but maybe this somewhat cryptic tweet means more to you than it does to me?

[It's available in the feed file that gets linked out of the gameday application rather than in the usual location.](https://twitter.com/brooksbaseball/status/609519326912188417)

**Comment by cpsievert** [comment]
Unfortunately these are hosted elsewhere in JSON format -> https://twitter.com/darenw/status/615928648676216832

**Comment by dlependorf** [comment]
Aha! Well, at least we know. Somewhat annoyingly, it looks like the batted ball velo/angle data is only held in the description (and description_es) text strings, not as separate field/values, but that probably isn't too hard to get around.

**Comment by cpsievert** [comment]
If anyone is interested in this, here is [a post you may find useful](https://baseballwithr.wordpress.com/2015/07/15/obtaining-exit-velocity-and-distance-of-batted-balls/)
