### ISSUE TITLE
Update scrape function to account for MLBAM's new trailing slash requirement

### ISSUE THREAD

**Issue by jrbattles** [cpsievert/pitchRx#57]
https://www.reddit.com/r/Sabermetrics/comments/7v07ax/mlb_gameday_data_sites_down_went_private/

**Comment by jrbattles** [comment]
This does NOT work.
http://gd2.mlb.com/components/game/mlb/year_2017/month_04/day_02/
This does work.
http://gd2.mlb.com/components/game/mlb/year_2017/month_04/day_02

**Comment by cpsievert** [comment]
That's a bummer. I don't really have the bandwidth for this project anymore...would love a pull request with a fix!

**Comment by jrbattles** [comment]
this seems to be only a problem for 2017 regular season data.

**Comment by Mpellet771** [comment]
I found where the code needs to be changed but am not sure how to submit the fix. Anyone else figure it out?

**Comment by cpsievert** [comment]
@Mpellet771 one way to submit a fix is to use the "edit this file" option 

![screen shot 2018-02-20 at 12 45 13 pm](https://user-images.githubusercontent.com/1365941/36442631-02e26e0c-163c-11e8-957a-4a168e89433e.png)

**Comment by cpsievert** [comment]
@Mpellet771 could you please point to where the fix needs to be made?

**Comment by cpsievert** [comment]
It looks like the real issue here is related to https://github.com/cpsievert/pitchRx/issues/58#issuecomment-372900373. Anyway, 4dcad301828ed3341ae7da55aa1237737af3c856 should at least solve the issue for 2017. Please update and give it a whirl!

**Comment by znmeb** [comment]
fixed in openWAR - https://github.com/beanumber/openWAR/pull/113

**Comment by jrbattles** [comment]
so this was fixed in openWAR but was it also fixed here in pitchRX?

**Comment by Mpellet771** [comment]
Here is where the issue is: 
Works: http://gd2.mlb.com/components/game/mlb/year_2019/month_03/day_23
Does not work: http://gd2.mlb.com/components/game/mlb/year_2019/month_03/day_23/

Even if I click a link at http://gd2.mlb.com/components/game/mlb/year_2019/month_03/, it tries to link with the forward slash, and then I get an error. The scraper needs to leave off the forward slash for the day link, get the game IDs, and then prepend the forward slash.

Thanks.
